# MAIN base
baseURL = "https://grincharge.vensam.com"
languageCode = "en-us"
title = "GrinCharge"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About Us"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "FAQ"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 3

# Footer Address
[params.address]
email = "sampathsatti@gmail.com"
phone = "091 8885918052"

# Footer Social
[params.social]
facebook = ""
twitter = ""
github = ""

[params]

# Header
logo = "images/GrinCharge_black.png"
fabFormURL = "https://fabform.io/f/wQQO1Xc"

# Footer
footerTitle = "To get in touch with us, please use the information below"
copyright1 = "All right reserved"
copyright2 = "Copyright Â© {year}"

#contact
email = "sampathsatti@gmail.com"
